(eval-when-compile    (require 'color-theme))
(defun errai2-theme ()
  "Color theme by errai, created 2015-09-11."
  (interactive)
  (color-theme-install
   '(errai2-theme
     ((background-color . "#171717")
      (background-mode . dark)
      (foreground-color . "#dfdfdf"))
     ((compilation-message-face . underline)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#171717" :foreground "#dfdfdf" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "cyan1"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "#dfdfdf"))))
     (compilation-column-number ((t (:foreground "#99ad6a"))))
     (compilation-error ((t (:foreground "#cf6a4c"))))
     (compilation-info ((t (:foreground "#fad07a"))))
     (compilation-line-number ((t (:foreground "#888888"))))
     (compilation-mode-line-exit ((t (:foreground "#99ad6a"))))
     (compilation-mode-line-fail ((t (:foreground "#cf6a4c"))))
     (compilation-mode-line-run ((t (:foreground "#fad07a"))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:underline t))))
     (completions-common-part ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#dfdfdf" :background "#171717" :stipple nil :height 1))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "white"))))
     (erlang-font-lock-exported-function-name-face ((t (:foreground "#fad07a"))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:bold t :weight bold :foreground "Pink"))))
     (flymake-warnline ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (font-lock-builtin-face ((t (:foreground "#8fbfdc"))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#888888"))))
     (font-lock-comment-face ((t (:italic t :foreground "#888888" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#ffb964"))))
     (font-lock-doc-face ((t (:foreground "#99ad6a"))))
     (font-lock-function-name-face ((t (:foreground "#fad07a"))))
     (font-lock-keyword-face ((t (:foreground "#8197bf"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#dfdfdf"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :foreground "#cf6a4c" :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :foreground "#fad07a" :weight bold))))
     (font-lock-string-face ((t (:foreground "#99ad6a"))))
     (font-lock-type-face ((t (:foreground "#ffb964"))))
     (font-lock-variable-name-face ((t (:foreground "#cf6a4c"))))
     (font-lock-warning-face ((t (:foreground "#dd0093"))))
     (fringe ((t (:background "#171717" :foreground "#dfdfdf"))))
     (glyphless-char ((t (:underline t))))
     (header-line ((t (:foreground "#dfdfdf"))))
     (help-argument-name ((t (:underline t))))
     (highlight ((t (:background "darkolivegreen"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (:underline t :foreground "cyan1"))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "#dd0093" :foreground "#dfdfdf"))))
     (isearch-fail ((t (:background "#dd0093"))))
     (italic ((t (:underline t))))
     (lazy-highlight ((t (:foreground "#dd0093"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "#dd0093"))))
	 ;;(menu ((t (:background "gray" :foreground "black"))))
	 ;;(menu ((t (:background "black" :foreground "#dfdfdf"))))
	 (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "#dfdfdf"))))
     (mode-line ((t (:foreground "#dfdfdf"))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:foreground "#363636"))))
     (mouse ((t (nil))))
     (neo-banner-face ((t (:bold t :foreground "lightblue" :weight bold))))
     (neo-button-face ((t (:underline nil))))
     (neo-dir-link-face ((t (:foreground "DeepSkyBlue"))))
     (neo-expand-btn-face ((t (:foreground "SkyBlue"))))
     (neo-file-link-face ((t (:foreground "White"))))
     (neo-header-face ((t (:foreground "White"))))
     (neo-root-dir-face ((t (:bold t :foreground "lightblue" :weight bold))))
     (neo-vc-added-face ((t (:foreground "LightGreen"))))
     (neo-vc-conflict-face ((t (:foreground "Red1"))))
     (neo-vc-default-face ((t (:foreground "White"))))
     (neo-vc-edited-face ((t (:foreground "Magenta"))))
     (neo-vc-ignored-face ((t (:foreground "DarkGrey"))))
     (neo-vc-missing-face ((t (:foreground "Red1"))))
     (neo-vc-needs-merge-face ((t (:foreground "Red1"))))
     (neo-vc-needs-update-face ((t (:underline t))))
     (neo-vc-removed-face ((t (:strike-through t))))
     (neo-vc-unlocked-changes-face ((t (:background "Blue" :foreground "Red"))))
     (neo-vc-unregistered-face ((t (nil))))
     (neo-vc-up-to-date-face ((t (:foreground "LightGray"))))
     (neo-vc-user-face ((t (:italic t :foreground "Red" :slant italic))))
     (next-error ((t (:background "gray20"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (query-replace ((t (:foreground "#dfdfdf" :background "#dd0093"))))
     (region ((t (:background "gray20"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (shadow ((t (:foreground "grey70"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (trailing-whitespace ((t (:background "#dd0093"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (:foreground "#363636"))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black")))))))
(add-to-list 'color-themes '(errai2-theme  "ERRAI2" "kukhyun"))
