(eval-when-compile    (require 'color-theme))
(defun errai-theme ()
  "Color theme by errai, created 2014-09-18."
  (interactive)
  (color-theme-install
   '(errai-theme
     ((background-color . "black")
      (background-mode . dark)
      (foreground-color . "White"))
     ((list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (compilation-column-number ((t (:foreground "green"))))
     (compilation-error ((t (:foreground "red"))))
     (compilation-info ((t (:bold t :foreground "green" :weight bold))))
     (compilation-line-number ((t (:foreground "yellow" :weight light))))
     (compilation-warning ((t (:bold t :foreground "cyan" :weight bold))))
     (completions-annotations ((t (:underline t))))
     (completions-common-part ((t (:background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :family "default"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (nil))))
     (erlang-font-lock-exported-function-name-face ((t (:bold t :weight bold :foreground "blue"))))
     (error ((t (:bold t :foreground "red" :weight bold))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "green"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#F75D59"))))
     (font-lock-comment-face ((t (:foreground "orangered"))))
     (font-lock-constant-face ((t (:foreground "magenta"))))
     (font-lock-doc-face ((t (:foreground "Green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "cyan" :weight bold))))
     (font-lock-negation-char-face ((t (:foreground "yellow"))))
     (font-lock-preprocessor-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-reference-face ((t (:foreground "green"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
;;     (font-lock-string-face ((t (:foreground "magenta4"))))
     (font-lock-string-face ((t (:foreground "#d700d7"))))
     (font-lock-type-face ((t (:foreground "blue"))))
     (font-lock-type-face-man ((t (:foreground "green"))))
     (font-lock-variable-name-face ((t (:foreground "green" :weight light))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "grey95"))))
     (glyphless-char ((t (:underline t))))
     (header-line ((t (:underline t))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "black"))))
     (ibuffer-marked-face ((t (:background "gray85"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (:foreground "blue" :underline t))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (:underline t :foreground "blue"))))
     (info-xref-visited ((t (:underline t :foreground "magenta4"))))
     (isearch ((t (:background "magenta4" :foreground "cyan1"))))
     (isearch-fail ((t (:background "red"))))
     (italic ((t (:underline t))))
     (lazy-highlight ((t (:background "turquoise3"))))
     (link ((t (:foreground "blue" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (magit-diff-add ((t (:foreground "MediumSlateBlue"))))
     (magit-diff-del ((t (:foreground "maroon"))))
     (magit-file-header ((t (:foreground "violet"))))
     (magit-header ((t (:foreground "cyan"))))
     (magit-hunk-header ((t (:foreground "blue"))))
     (magit-log-head-label-local ((t (:foreground "#3387cc"))))
     (magit-log-head-label-remote ((t (:foreground "#65b042"))))
     (magit-log-head-label-tags ((t (:background "#cf6a4c" :foreground "black"))))
     (magit-log-sha1 ((t (:foreground "#cf6a4c"))))
     (magit-tag-label ((t (:background "blue" :foreground "orange"))))
     (match ((t (:background "yellow" :foreground "black"))))
     ;;(menu ((t (:background "gray" :foreground "black"))))
	 (menu ((t (nil))))
     (minibuffer-marked-face ((t (:background "medium blue"))))
     (minibuffer-prompt ((t (:foreground "blue"))))
     (mode-line ((t (nil))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:background "green" :foreground "black"))))
     (mode-line-inactive ((t (nil))))
     (mouse ((t (nil))))
     (next-error ((t (:background "blue" :foreground "white"))))
     (nobreak-space ((t (:background "magenta"))))
     (query-replace ((t (:background "magenta4" :foreground "cyan1"))))
     (region ((t (:background "blue" :foreground "white"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "black"))))
     (shadow ((t (:foreground "green"))))
     (success ((t (:bold t :foreground "green" :weight bold))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black" :family "helv"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "green"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black"))))
     (zmacs-region ((t (:background "gray65")))))))
(add-to-list 'color-themes '(errai-theme  "errai-theme" "ERRAI"))
